version: '3.8'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: 'ingemark'
      POSTGRES_PASSWORD: 'ingemark'
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    volumes:
      - persistent:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    logging:
      driver: "none"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:5050



#  ingemark:
#    restart: always
#    build: .
#    ports:
#      - "8080:8080"
#   # environment:
#    #SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
#    depends_on:
#      - postgres

volumes:
  persistent:
  pgadmin-data:




