version: '2.4'

services:

  postgres:
    container_name: postgres
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: 'ingemark'
      POSTGRES_PASSWORD: 'ingemark'
      POSTGRES_DB: 'ingemark'
    ports:
      - "5432:5432"
    command: postgres -c listen_addresses='*'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ingemark" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - persistent:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    logging:
      driver: "none"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:5050



  ingemark:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  persistent:
  pgadmin-data:




